test: niuxianghui
xianghui: test
configserver:
    name: JHipster Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/jhipster/jhipster-registry-sample-config !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: xianghui.niu
                #secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
